# جریان کار برای ساخت و استقرار یک سایت جییل به صفحه های گیتهاب
نام:  Deploy Jekyll با GitHub Pages

on:
  # روی فشار شاخه پیش فرض را هدف قرار می دهند
  فشار :
  شعبه ها  :   ["اصلی"]

  # اجازه می دهید که این جریان کار را به صورت دستی از طریق عمل ها انجام دهید
  جریان کار_ارسال :

#س ها اجازه های GITHUB_TOKEN برای اجازه استقرار به صفحه های GitHub
اجازه:
  محتویات  :   می خواند
 صفحات  :   بنویسید
  نشانه های id  :   بنویسید

#تنها یک استقرار همزمان، در حال حرکت، در حال صف بندی بین جریان های درون مرحله و آخرین صف بندی شده است.
با این حال، این کار را در حال حاضر لغو کنید، همان طور که می خواهیم اجازه دهیم این استقرار تولید کامل شود.
هم زمان:
  گروه  :   "صفحات"
  لغو  :   اشتباه

شغل:
   کار ساخت 
  ساخت :
    runs-on:  آخرین بار
  قدم ها :
         -    نام  :    بررسی
  استفاده  :   اقدامات/checkout@v4
         -    نام  :    صفحات را مرتب کنید
  استفاده  :   اعمال/پیکره صفحات@v5
         -    نام  :    ساخته شده با جکیل
  استفاده  :   اقدامات/jekyll-build-page@v1
  با :
  منبع  :   ./
 مقصد    :   ./_site:  /_ 
        -   نام   :    به آپدیت :   به روز رسانی    
 استفاده    :   اقدامات/upload-pages-artifact@v3:  اعمال/upload-صفحه-artifact@v3 

 کار کار
  deploy:
  محیط زیست :
 نام    :   صفحات:  صفحات github 
      url  :    $ :   ${ _ deployment.outputs.page_url   {{   steps.deployment.outputs.page_url   }}
    runs-on  :    آخرین بار :   ubuntu-آخرین 
 نیاز    :   ساخت:  ساخت   
  قدم ها :
         -    نام   :    به صفحه های گیتهاب :   به صفحه های GitHub    
        id  :    استقرار :   استقرار   
 استفاده    :   اقدامات/پست-صفحات@v4:  اعمال/deploy-صفحات@v4 
